# **National Unversity Of Technology (NUTECH), Islamabad**
## **Department Of Artificial Intelligence**
## Course Code: CS381
## Course: ANN & Deep Learning Lab
## Instructor: Dr Benish/Engr.M Haseeb Khan
## Lab Title:  Lab 01 : Introduction to Neural Network Environments and Tensor Operations

**Objective:** Get hands-on with tensors: creation, basic ops, reshaping, and automatic differentiation (gradients) — using either **PyTorch** or **TensorFlow/Keras** in **Google Colab**.

**What you'll do**
1. Set up the environment in Colab (CPU/GPU), verify versions.
2. Create tensors: scalar, vector, 3×3 matrix (random), and a 3‑D tensor (2×3×4).
3. Run core ops: element‑wise add/mul, matrix multiplication, mean & sum.
4. Reshape a 1‑D tensor (12 elems) into 3×4 and 2×6.
5. Compute gradients for **y = x²** using autograd (PyTorch) and GradientTape (TensorFlow).

> 💡 **Tip**: You can complete the lab in **either** framework. Both PyTorch and TensorFlow solutions are included below.

### Table of Contents
0. [Colab Runtime Setup (CPU/GPU)](#0-colab-runtime-setup-cpugpu)
1. [Tensor Initializations](#1-tensor-initializations)
2. [Core Tensor Operations](#2-core-tensor-operations)
3. [Reshaping](#3-reshaping)
4. [Gradients: Automatic Differentiation](#4-gradients-automatic-differentiation)
5. [Post-Lab Tasks: Scenario-Based](#post-lab-tasks-scenario-based)
    - [Scenario 1: Image Processing (Tensors & Operations)(PyTorch)](#scenario-1-image-processing-tensors--operations)
    - [Scenario 2: Data Analysis (Reshaping & Aggregation)(PyTorch)](#scenario-2-data-analysis-reshaping--aggregation)
    - [Scenario 1: Image Processing (Tensors & Operations)(TensorFlow)](#scenario-1-image-processing-tensors--operations)
    - [Scenario 2: Data Analysis (Reshaping & Aggregation)(TensorFlow)](#scenario-2-data-analysis-reshaping--aggregation)
6. [Common Pitfalls](#common-pitfalls)

## 0) Colab Runtime Setup (CPU/GPU)
- *(Optional but recommended)* **Enable GPU:** `Runtime → Change runtime type → Hardware accelerator: GPU`, then re-run the next cell.
- You don’t need Conda in Colab; use `pip` inside the notebook if you need specific versions.

In [ ]:
# 0.1 — Environment & Version Check (safe to run multiple times)
import sys, platform

print("Python:", sys.version.split()[0])
print("OS:", platform.platform())

# Try importing, but do not fail the notebook if one library is missing.
torch, tf = None, None

try:
    import torch
    print("PyTorch:", torch.__version__)
    print("CUDA available (torch):", torch.cuda.is_available())
    if torch.cuda.is_available():
        print("CUDA device:", torch.cuda.get_device_name(0))
except Exception as e:
    print("PyTorch not available:", e)

try:
    import tensorflow as tf
    print("TensorFlow:", tf.__version__)
    gpus = tf.config.list_physical_devices('GPU')
    print("GPUs (tf):", gpus)
except Exception as e:
    print("TensorFlow not available:", e)

print("\nIf a framework is missing or version isn't as expected, you can install with pip, e.g.:")
print("!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121")
print("!pip install tensorflow==2.16.*  # (example)")

Python: 3.12.11
OS: Linux-6.1.123+-x86_64-with-glibc2.35
PyTorch: 2.8.0+cu126
CUDA available (torch): True
CUDA device: Tesla T4
TensorFlow: 2.19.0
GPUs (tf): [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

If a framework is missing or version isn't as expected, you can install with pip, e.g.:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip install tensorflow==2.16.*  # (example)


*   `import sys, platform`: Imports the `sys` and `platform` modules, which provide access to system-specific parameters and functions.
*   `print("Python:", sys.version.split()[0])`: Prints the Python version being used. `sys.version` gives a detailed string, and `.split()[0]` extracts just the version number.
*   `print("OS:", platform.platform())`: Prints the operating system information.
*   `torch, tf = None, None`: Initializes the variables `torch` and `tf` to `None`. This is done before the `try...except` blocks to ensure these variables exist even if the imports fail.
*   `try:`: Starts a try block to attempt importing PyTorch.
*   `import torch`: Attempts to import the PyTorch library.
*   `print("PyTorch:", torch.__version__)`: If the import is successful, prints the installed PyTorch version.
*   `print("CUDA available (torch):", torch.cuda.is_available())`: Checks and prints if a CUDA-enabled GPU is available for PyTorch.
*   `if torch.cuda.is_available():`: If a CUDA GPU is available...
*   `print("CUDA device:", torch.cuda.get_device_name(0))`: Prints the name of the CUDA device (GPU).
*   `except Exception as e:`: If any exception occurs during the PyTorch import or checks...
*   `print("PyTorch not available:", e)`: Prints a message indicating PyTorch is not available and shows the error.
*   `try:`: Starts a try block to attempt importing TensorFlow.
*   `import tensorflow as tf`: Attempts to import the TensorFlow library and assigns it the alias `tf`.
*   `print("TensorFlow:", tf.__version__)`: If the import is successful, prints the installed TensorFlow version.
*   `gpus = tf.config.list_physical_devices('GPU')`: Gets a list of physical GPU devices available to TensorFlow.
*   `print("GPUs (tf):", gpus)`: Prints the list of available GPUs found by TensorFlow.
*   `except Exception as e:`: If any exception occurs during the TensorFlow import or checks...
*   `print("TensorFlow not available:", e)`: Prints a message indicating TensorFlow is not available and shows the error.
*   `print("\nIf a framework is missing or version isn't as expected, you can install with pip, e.g.:")`: Prints a message about how to install frameworks using pip.
*   `print("!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121")`: Provides an example pip command to install PyTorch with CUDA support.
*   `print("!pip install tensorflow==2.16.* # (example)")`: Provides an example pip command to install a specific version of TensorFlow.

## 1) Tensor Initializations
Create the following in **PyTorch** and/or **TensorFlow**:
a) Scalar (0‑D)  
b) Vector (1‑D) with 5 elements  
c) 3×3 random matrix (2‑D)  
d) 3‑D tensor of shape **2×3×4**

In [ ]:
# 1A — PyTorch Initializations
import torch

print("=== PyTorch Initializations ===")
# a) Scalar (0-D)
scalar_t = torch.tensor(3.14)
print("Scalar (0-D):", scalar_t, "| ndim:", scalar_t.ndim, "| shape:", tuple(scalar_t.shape))

# b) Vector (1-D, 5 elements)
vector_t = torch.arange(1, 6)  # [1,2,3,4,5]
print("Vector (1-D):", vector_t, "| ndim:", vector_t.ndim, "| shape:", tuple(vector_t.shape))

# c) 3x3 random matrix (2-D)
torch.manual_seed(42)  # reproducibility
matrix_t = torch.rand(3, 3)
print("3x3 Random Matrix (2-D):\n", matrix_t, "\nndim:", matrix_t.ndim, "shape:", tuple(matrix_t.shape))

# d) 3-D tensor with shape 2x3x4
tensor3d_t = torch.zeros(2, 3, 4)  # or torch.randn(2,3,4)
print("3-D Tensor (2x3x4):\n", tensor3d_t, "\nndim:", tensor3d_t.ndim, "shape:", tuple(tensor3d_t.shape))

=== PyTorch Initializations ===
Scalar (0-D): tensor(3.1400) | ndim: 0 | shape: ()
Vector (1-D): tensor([1, 2, 3, 4, 5]) | ndim: 1 | shape: (5,)
3x3 Random Matrix (2-D):
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]]) 
ndim: 2 shape: (3, 3)
3-D Tensor (2x3x4):
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]) 
ndim: 3 shape: (2, 3, 4)


*   `import torch`: Imports the PyTorch library.
*   `print("=== PyTorch Initializations ===")`: Prints a header to indicate the start of PyTorch initializations.
*   `scalar_t = torch.tensor(3.14)`: Creates a PyTorch scalar tensor with the value 3.14.
*   `print("Scalar (0-D):", scalar_t, "| ndim:", scalar_t.ndim, "| shape:", tuple(scalar_t.shape))`: Prints the scalar tensor, its number of dimensions (`ndim`), and its shape.
*   `vector_t = torch.arange(1, 6)`: Creates a 1-D PyTorch tensor (a vector) with values ranging from 1 up to (but not including) 6.
*   `print("Vector (1-D):", vector_t, "| ndim:", vector_t.ndim, "| shape:", tuple(vector_t.shape))`: Prints the vector tensor, its number of dimensions, and its shape.
*   `torch.manual_seed(42)`: Sets the seed for the random number generator for reproducibility of random tensor creation.
*   `matrix_t = torch.rand(3, 3)`: Creates a 3x3 2-D PyTorch tensor (a matrix) with random values between 0 and 1.
*   `print("3x3 Random Matrix (2-D):\n", matrix_t, "\nndim:", matrix_t.ndim, "shape:", tuple(matrix_t.shape))`: Prints the random matrix, its number of dimensions, and its shape.
*   `tensor3d_t = torch.zeros(2, 3, 4)`: Creates a 3-D PyTorch tensor with shape 2x3x4, filled with zeros.
*   `print("3-D Tensor (2x3x4):\n", tensor3d_t, "\nndim:", tensor3d_t.ndim, "shape:", tuple(tensor3d_t.shape))`: Prints the 3-D tensor, its number of dimensions, and its shape.

In [ ]:
# 1B — TensorFlow Initializations
import tensorflow as tf

print("=== TensorFlow Initializations ===")
# a) Scalar (0-D)
scalar_tf = tf.constant(3.14)
print("Scalar (0-D):", scalar_tf, "| ndim:", scalar_tf.ndim, "| shape:", scalar_tf.shape)

# b) Vector (1-D, 5 elements)
vector_tf = tf.range(1, 6)  # [1,2,3,4,5]
print("Vector (1-D):", vector_tf, "| ndim:", vector_tf.ndim, "| shape:", vector_tf.shape)

# c) 3x3 random matrix (2-D)
tf.random.set_seed(42)  # reproducibility
matrix_tf = tf.random.uniform((3, 3))
print("3x3 Random Matrix (2-D):\n", matrix_tf, "\nndim:", matrix_tf.ndim, "shape:", matrix_tf.shape)

# d) 3-D tensor with shape 2x3x4
tensor3d_tf = tf.zeros((2, 3, 4))
print("3-D Tensor (2x3x4):\n", tensor3d_tf, "\nndim:", tensor3d_tf.ndim, "shape:", tensor3d_tf.shape)

=== TensorFlow Initializations ===
Scalar (0-D): tf.Tensor(3.14, shape=(), dtype=float32) | ndim: 0 | shape: ()
Vector (1-D): tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32) | ndim: 1 | shape: (5,)
3x3 Random Matrix (2-D):
 tf.Tensor(
[[0.6645621  0.44100678 0.3528825 ]
 [0.46448255 0.03366041 0.68467236]
 [0.74011743 0.8724445  0.22632635]], shape=(3, 3), dtype=float32) 
ndim: 2 shape: (3, 3)
3-D Tensor (2x3x4):
 tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(2, 3, 4), dtype=float32) 
ndim: 3 shape: (2, 3, 4)


*   `import tensorflow as tf`: Imports the TensorFlow library and assigns it the alias `tf`.
*   `print("=== TensorFlow Initializations ===")`: Prints a header to indicate the start of TensorFlow initializations.
*   `scalar_tf = tf.constant(3.14)`: Creates a TensorFlow scalar tensor with the value 3.14. `tf.constant` is used for tensors whose values won't change.
*   `print("Scalar (0-D):", scalar_tf, "| ndim:", scalar_tf.ndim, "| shape:", scalar_tf.shape)`: Prints the scalar tensor, its number of dimensions (`ndim`), and its shape.
*   `vector_tf = tf.range(1, 6)`: Creates a 1-D TensorFlow tensor (a vector) with values ranging from 1 up to (but not including) 6.
*   `print("Vector (1-D):", vector_tf, "| ndim:", vector_tf.ndim, "| shape:", vector_tf.shape)`: Prints the vector tensor, its number of dimensions, and its shape.
*   `tf.random.set_seed(42)`: Sets the seed for the random number generator for reproducibility of random tensor creation in TensorFlow.
*   `matrix_tf = tf.random.uniform((3, 3))`: Creates a 3x3 2-D TensorFlow tensor (a matrix) with random values uniformly distributed between 0 and 1.
*   `print("3x3 Random Matrix (2-D):\n", matrix_tf, "\nndim:", matrix_tf.ndim, "shape:", matrix_tf.shape)`: Prints the random matrix, its number of dimensions, and its shape. `.numpy()` is often used to get the NumPy representation for clearer printing of tensor contents.
*   `tensor3d_tf = tf.zeros((2, 3, 4))`: Creates a 3-D TensorFlow tensor with shape 2x3x4, filled with zeros.
*   `print("3-D Tensor (2x3x4):\n", tensor3d_tf, "\nndim:", tensor3d_tf.ndim, "shape:", tensor3d_tf.shape)`: Prints the 3-D tensor, its number of dimensions, and its shape.

## 2) Core Tensor Operations
Perform and print the results of:
a) **Element-wise addition** and **multiplication** on same-shape tensors  
b) **Matrix multiplication** (dot product) of compatible 2‑D tensors  
c) **Mean** and **Sum** over all elements

In [ ]:
# 2A — PyTorch: Element-wise ops, Matmul, Mean, Sum
import torch

A = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])
B = torch.tensor([[10., 20., 30.],
                  [40., 50., 60.]])

print("A:\n", A)
print("B:\n", B)

# a) Element-wise
add_AB = A + B
mul_AB = A * B
print("\nElement-wise Add:\n", add_AB)
print("Element-wise Mul:\n", mul_AB)

# b) Matrix multiplication (2x3) @ (3x2) -> (2x2)
C = torch.tensor([[1., 2.],
                  [3., 4.],
                  [5., 6.]])
matmul_result = A @ C  # or torch.matmul(A, C)
print("\nMatrix Multiplication A @ C:\n", matmul_result)

# c) Mean & Sum (on A)
print("\nMean(A):", A.mean().item())
print("Sum(A):", A.sum().item())

A:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
B:
 tensor([[10., 20., 30.],
        [40., 50., 60.]])

Element-wise Add:
 tensor([[11., 22., 33.],
        [44., 55., 66.]])
Element-wise Mul:
 tensor([[ 10.,  40.,  90.],
        [160., 250., 360.]])

Matrix Multiplication A @ C:
 tensor([[22., 28.],
        [49., 64.]])

Mean(A): 3.5
Sum(A): 21.0


*   `import torch`: Imports the PyTorch library.
*   `A = torch.tensor([[1., 2., 3.], [4., 5., 6.]])`: Creates a 2x3 PyTorch tensor `A`.
*   `B = torch.tensor([[10., 20., 30.], [40., 50., 60.]])`: Creates another 2x3 PyTorch tensor `B`.
*   `print("A:\n", A)`: Prints the tensor `A`.
*   `print("B:\n", B)`: Prints the tensor `B`.
*   `add_AB = A + B`: Performs element-wise addition of tensors `A` and `B`.
*   `mul_AB = A * B`: Performs element-wise multiplication of tensors `A` and `B`.
*   `print("\nElement-wise Add:\n", add_AB)`: Prints the result of element-wise addition.
*   `print("Element-wise Mul:\n", mul_AB)`: Prints the result of element-wise multiplication.
*   `C = torch.tensor([[1., 2.], [3., 4.], [5., 6.]])`: Creates a 3x2 PyTorch tensor `C` for matrix multiplication.
*   `matmul_result = A @ C  # or torch.matmul(A, C)`: Performs matrix multiplication of `A` (2x3) and `C` (3x2), resulting in a 2x2 tensor. The `@` operator is a shorthand for matrix multiplication in PyTorch.
*   `print("\nMatrix Multiplication A @ C:\n", matmul_result)`: Prints the result of the matrix multiplication.
*   `print("\nMean(A):", A.mean().item())`: Calculates the mean of all elements in tensor `A` and uses `.item()` to get the scalar value.
*   `print("Sum(A):", A.sum().item())`: Calculates the sum of all elements in tensor `A` and uses `.item()` to get the scalar value.

In [ ]:
# 2B — TensorFlow: Element-wise ops, Matmul, Mean, Sum
import tensorflow as tf

A = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])
B = tf.constant([[10., 20., 30.],
                 [40., 50., 60.]])

print("A:\n", A.numpy())
print("B:\n", B.numpy())

# a) Element-wise
add_AB = A + B
mul_AB = A * B
print("\nElement-wise Add:\n", add_AB.numpy())
print("Element-wise Mul:\n", mul_AB.numpy())

# b) Matrix multiplication (2x3) x (3x2) -> (2x2)
C = tf.constant([[1., 2.],
                 [3., 4.],
                 [5., 6.]])
matmul_result = tf.matmul(A, C)
print("\nMatrix Multiplication A @ C:\n", matmul_result.numpy())

# c) Mean & Sum (on A)
print("\nMean(A):", tf.reduce_mean(A).numpy())
print("Sum(A):", tf.reduce_sum(A).numpy())

A:
 [[1. 2. 3.]
 [4. 5. 6.]]
B:
 [[10. 20. 30.]
 [40. 50. 60.]]

Element-wise Add:
 [[11. 22. 33.]
 [44. 55. 66.]]
Element-wise Mul:
 [[ 10.  40.  90.]
 [160. 250. 360.]]

Matrix Multiplication A @ C:
 [[22. 28.]
 [49. 64.]]

Mean(A): 3.5
Sum(A): 21.0


*   `import tensorflow as tf`: Imports the TensorFlow library and assigns it the alias `tf`.
*   `A = tf.constant([[1., 2., 3.], [4., 5., 6.]])`: Creates a 2x3 TensorFlow tensor `A` using `tf.constant`.
*   `B = tf.constant([[10., 20., 30.], [40., 50., 60.]])`: Creates another 2x3 TensorFlow tensor `B` using `tf.constant`.
*   `print("A:\n", A.numpy())`: Prints the tensor `A`. `.numpy()` is used to get the NumPy array representation for printing.
*   `print("B:\n", B.numpy())`: Prints the tensor `B` using `.numpy()`.
*   `add_AB = A + B`: Performs element-wise addition of tensors `A` and `B`.
*   `mul_AB = A * B`: Performs element-wise multiplication of tensors `A` and `B`.
*   `print("\nElement-wise Add:\n", add_AB.numpy())`: Prints the result of element-wise addition using `.numpy()`.
*   `print("Element-wise Mul:\n", mul_AB.numpy())`: Prints the result of element-wise multiplication using `.numpy()`.
*   `C = tf.constant([[1., 2.], [3., 4.], [5., 6.]])`: Creates a 3x2 TensorFlow tensor `C` for matrix multiplication using `tf.constant`.
*   `matmul_result = tf.matmul(A, C)`: Performs matrix multiplication of `A` (2x3) and `C` (3x2), resulting in a 2x2 tensor, using `tf.matmul()`.
*   `print("\nMatrix Multiplication A @ C:\n", matmul_result.numpy())`: Prints the result of the matrix multiplication using `.numpy()`.
*   `print("\nMean(A):", tf.reduce_mean(A).numpy())`: Calculates the mean of all elements in tensor `A` using `tf.reduce_mean()` and gets the scalar value with `.numpy()`.
*   `print("Sum(A):", tf.reduce_sum(A).numpy())`: Calculates the sum of all elements in tensor `A` using `tf.reduce_sum()` and gets the scalar value with `.numpy()`.

## 3) Reshaping
Create a 1‑D tensor with **12 elements** and reshape it to **3×4** and **2×6**. Note: In PyTorch, `.reshape` may return views; `.view` requires contiguous tensors. In TensorFlow, use `tf.reshape`. Verify shapes and understand that reshaping does **not** change the data order by default (row-major).

In [ ]:
# 3A — PyTorch Reshaping
import torch

x = torch.arange(1, 13)  # [1..12]
print("x:", x, "| shape:", tuple(x.shape))

x_3x4 = x.reshape(3, 4)
x_2x6 = x.reshape(2, 6)
print("\nReshaped to 3x4:\n", x_3x4, "| shape:", tuple(x_3x4.shape))
print("\nReshaped to 2x6:\n", x_2x6, "| shape:", tuple(x_2x6.shape))

x: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]) | shape: (12,)

Reshaped to 3x4:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]) | shape: (3, 4)

Reshaped to 2x6:
 tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]) | shape: (2, 6)


*   `import torch`: Imports the PyTorch library.
*   `x = torch.arange(1, 13)`: Creates a 1-D PyTorch tensor `x` with values from 1 up to (but not including) 13, effectively creating a tensor with elements 1 through 12.
*   `print("x:", x, "| shape:", tuple(x.shape))`: Prints the original 1-D tensor `x` and its shape.
*   `x_3x4 = x.reshape(3, 4)`: Reshapes the 1-D tensor `x` into a 2-D tensor with a shape of 3 rows and 4 columns. The elements are filled in row-major order.
*   `x_2x6 = x.reshape(2, 6)`: Reshapes the original 1-D tensor `x` into a 2-D tensor with a shape of 2 rows and 6 columns. The elements are filled in row-major order.
*   `print("\nReshaped to 3x4:\n", x_3x4, "| shape:", tuple(x_3x4.shape))`: Prints the tensor reshaped to 3x4 and its new shape.
*   `print("\nReshaped to 2x6:\n", x_2x6, "| shape:", tuple(x_2x6.shape))`: Prints the tensor reshaped to 2x6 and its new shape.

In [ ]:
# 3B — TensorFlow Reshaping
import tensorflow as tf

x = tf.range(1, 13)  # [1..12]
print("x:", x.numpy(), "| shape:", x.shape)

x_3x4 = tf.reshape(x, (3, 4))
x_2x6 = tf.reshape(x, (2, 6))
print("\nReshaped to 3x4:\n", x_3x4.numpy(), "| shape:", x_3x4.shape)
print("\nReshaped to 2x6:\n", x_2x6.numpy(), "| shape:", x_2x6.shape)

x: [ 1  2  3  4  5  6  7  8  9 10 11 12] | shape: (12,)

Reshaped to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] | shape: (3, 4)

Reshaped to 2x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] | shape: (2, 6)


*   `import tensorflow as tf`: Imports the TensorFlow library and assigns it the alias `tf`.
*   `x = tf.range(1, 13)`: Creates a 1-D TensorFlow tensor `x` with values from 1 up to (but not including) 13, effectively creating a tensor with elements 1 through 12.
*   `print("x:", x.numpy(), "| shape:", x.shape)`: Prints the original 1-D tensor `x` and its shape. `.numpy()` is used to display the tensor's contents as a NumPy array.
*   `x_3x4 = tf.reshape(x, (3, 4))`: Reshapes the 1-D tensor `x` into a 2-D tensor with a shape of 3 rows and 4 columns using `tf.reshape`. The elements are filled in row-major order.
*   `x_2x6 = tf.reshape(x, (2, 6))`: Reshapes the original 1-D tensor `x` into a 2-D tensor with a shape of 2 rows and 6 columns using `tf.reshape`. The elements are filled in row-major order.
*   `print("\nReshaped to 3x4:\n", x_3x4.numpy(), "| shape:", x_3x4.shape)`: Prints the tensor reshaped to 3x4 and its new shape using `.numpy()`.
*   `print("\nReshaped to 2x6:\n", x_2x6.numpy(), "| shape:", x_2x6.shape)`: Prints the tensor reshaped to 2x6 and its new shape using `.numpy()`.

## 4) Gradients: Automatic Differentiation
Compute the gradient of **y = x²** w.r.t. **x** at a chosen value (e.g., x=3.0).

- **PyTorch** uses `requires_grad=True` and `y.backward()`.
- **TensorFlow** uses `tf.GradientTape()`.

In [ ]:
# 4A — PyTorch Autograd (y = x^2)
import torch

x = torch.tensor(3.0, requires_grad=True)
y = x**2  # y = x^2
y.backward()          # dy/dx at x=3
print("x:", x.item(), " y:", y.item(), " dy/dx:", x.grad.item())  # dy/dx should be 2x = 6

x: 3.0  y: 9.0  dy/dx: 6.0


*   `import torch`: Imports the PyTorch library.
*   `x = torch.tensor(3.0, requires_grad=True)`: Creates a PyTorch scalar tensor `x` with the value 3.0. `requires_grad=True` is crucial here as it tells PyTorch to track operations on this tensor so that gradients can be computed later.
*   `y = x**2  # y = x^2`: Computes the value of `y` as the square of `x`. Since `y` is computed from a tensor that requires gradients, PyTorch will build a computation graph to track this operation.
*   `y.backward()`: This is the core of backpropagation. It computes the gradients of `y` with respect to all tensors that have `requires_grad=True` in the computation graph leading to `y`. In this case, it computes the gradient of `y` with respect to `x`.
*   `print("x:", x.item(), " y:", y.item(), " dy/dx:", x.grad.item())`: Prints the original value of `x`, the computed value of `y`, and the computed gradient of `y` with respect to `x`. `.item()` is used to extract the scalar value from a tensor. `x.grad` stores the computed gradient after `y.backward()` is called.

In [ ]:
# 4B — TensorFlow GradientTape (y = x^2)
import tensorflow as tf

x = tf.Variable(3.0)
with tf.GradientTape() as tape:
    y = x**2        # y = x^2
dy_dx = tape.gradient(y, x)  # dy/dx
print("x:", x.numpy(), " y:", y.numpy(), " dy/dx:", dy_dx.numpy())  # should be 6

x: 3.0  y: 9.0  dy/dx: 6.0


*   `import tensorflow as tf`: Imports the TensorFlow library and assigns it the alias `tf`.
*   `x = tf.Variable(3.0)`: Creates a TensorFlow `Variable` named `x` with an initial value of 3.0. `tf.Variable` is used for tensors whose values can be changed (like model parameters) and are automatically tracked for gradient computation.
*   `with tf.GradientTape() as tape:`: This creates a `tf.GradientTape` context. All operations performed on `tf.Variable`s within this `with` block are recorded by the tape, allowing for gradient computation later.
*   `y = x**2 # y = x^2`: Computes the value of `y` as the square of `x` within the `GradientTape` context. This operation is recorded by the tape.
*   `dy_dx = tape.gradient(y, x)`: This is the core of gradient computation in TensorFlow. It calculates the gradient of `y` with respect to `x`, using the operations recorded by the `tape`.
*   `print("x:", x.numpy(), " y:", y.numpy(), " dy/dx:", dy_dx.numpy())`: Prints the value of `x`, the computed value of `y`, and the computed gradient of `y` with respect to `x`. `.numpy()` is used to extract the scalar value from the TensorFlow tensors for printing.

## Post-Lab Tasks: Scenario-Based

Let's apply what you've learned about tensors and gradients in a few practical scenarios. Choose either PyTorch or TensorFlow for these tasks.

###**Scenario 1: Image Processing (Tensors & Operations) (Pytorch)**

Imagine you're working with a grayscale image represented as a 2D tensor (matrix). The intensity of each pixel is a value between 0 (black) and 255 (white).

1.  **Loading/Creating a Sample Image:** Create a 5x5 tensor to represent a small grayscale image. You can fill it with arbitrary integer values between 0 and 255.
2.  **Normalizing Pixel Values:** To prepare for machine learning, pixel values are often normalized to be between 0 and 1. Create a new tensor where each pixel value is divided by 255.
3.  **Applying a Simple Filter:** A basic image filter can be represented as another tensor (a kernel). Create a 3x3 kernel tensor (e.g., for blurring or edge detection - you can use simple values like all 1s or a central 1 with surrounding -1s). *Note: Applying a filter fully involves convolution, which is more advanced. For this task, simply perform element-wise multiplication of a section of the image with the kernel.* Select a 3x3 region from your normalized image tensor and perform element-wise multiplication with your kernel.
4.  **Calculating Average Brightness:** Calculate the mean pixel value of the *entire* normalized image tensor to get an idea of its overall brightness.


In [ ]:
# Scenario 1: Image Processing (PyTorch Solution)
import torch

print("--- Scenario 1: Image Processing (PyTorch) ---")

# 1. Loading/Creating a Sample Image (5x5)
image_t = torch.randint(0, 256, (5, 5), dtype=torch.float32)
print("Original Image Tensor:\n", image_t)

# 2. Normalizing Pixel Values (0 to 1)
normalized_image_t = image_t / 255.0
print("\nNormalized Image Tensor:\n", normalized_image_t)

# 3. Applying a Simple Filter (Element-wise multiplication of a 3x3 region)
kernel_t = torch.tensor([[1., 1., 1.],
                         [1., -8., 1.],
                         [1., 1., 1.]]) # Example edge detection kernel

# Select a 3x3 region (e.g., top-left corner)
image_region = normalized_image_t[0:3, 0:3]
filtered_region = image_region * kernel_t
print("\nSelected Image Region (3x3):\n", image_region)
print("Kernel:\n", kernel_t)
print("Filtered Region (Element-wise):\n", filtered_region)

# 4. Calculating Average Brightness of the entire normalized image
average_brightness_t = torch.mean(normalized_image_t)
print("\nAverage Brightness of Normalized Image:", average_brightness_t.item())

--- Scenario 1: Image Processing (PyTorch) ---
Original Image Tensor:
 tensor([[121., 210., 214.,  74., 202.],
        [ 87., 116.,  99., 103., 151.],
        [130., 149.,  52.,   1.,  87.],
        [235., 157.,  37., 129., 191.],
        [187.,  20., 160., 203.,  57.]])

Normalized Image Tensor:
 tensor([[0.4745, 0.8235, 0.8392, 0.2902, 0.7922],
        [0.3412, 0.4549, 0.3882, 0.4039, 0.5922],
        [0.5098, 0.5843, 0.2039, 0.0039, 0.3412],
        [0.9216, 0.6157, 0.1451, 0.5059, 0.7490],
        [0.7333, 0.0784, 0.6275, 0.7961, 0.2235]])

Selected Image Region (3x3):
 tensor([[0.4745, 0.8235, 0.8392],
        [0.3412, 0.4549, 0.3882],
        [0.5098, 0.5843, 0.2039]])
Kernel:
 tensor([[ 1.,  1.,  1.],
        [ 1., -8.,  1.],
        [ 1.,  1.,  1.]])
Filtered Region (Element-wise):
 tensor([[ 0.4745,  0.8235,  0.8392],
        [ 0.3412, -3.6392,  0.3882],
        [ 0.5098,  0.5843,  0.2039]])

Average Brightness of Normalized Image: 0.49756866693496704



###**Scenario 2: Data Analysis (Reshaping & Aggregation) (Pytorch)**

You have collected sensor data in a long, flat sequence, but you know the data was recorded in batches.

1.  **Create Sensor Data:** Create a 1D tensor containing 30 sequential data points (you can use `arange` or random values).
2.  **Reshape into Batches:** You know the data was collected in 6 batches of 5 readings each. Reshape the 1D tensor into a 2D tensor where each row represents a batch.
3.  **Calculate Batch Averages:** Compute the average reading for each batch (i.e., the mean of each row in your 2D tensor).
4.  **Reshape for Analysis:** You also want to analyze the data by the type of reading, knowing that the 5 readings in each batch correspond to 5 different sensor types. Reshape the original 1D tensor into a 2D tensor where each column represents a sensor type (you'll need to figure out the correct shape for this!).
5.  **Calculate Sensor Type Averages:** Compute the average reading for each sensor type (i.e., the mean of each column in this new 2D tensor).

In [ ]:
# Scenario 2: Data Analysis (PyTorch Solution)
import torch

print("\n--- Scenario 3: Data Analysis (PyTorch) ---")

# 1. Create Sensor Data (1D tensor, 30 elements)
sensor_data_1d_t = torch.arange(1, 31, dtype=torch.float32)
print("Original 1D Sensor Data:", sensor_data_1d_t)
print("Shape:", tuple(sensor_data_1d_t.shape))

# 2. Reshape into Batches (6 batches of 5 readings)
batches_2d_t = sensor_data_1d_t.reshape(6, 5)
print("\nReshaped into Batches (6x5):\n", batches_2d_t)
print("Shape:", tuple(batches_2d_t.shape))

# 3. Calculate Batch Averages (mean of each row)
batch_averages_t = torch.mean(batches_2d_t, dim=1) # dim=1 for mean across columns (each row)
print("\nBatch Averages:", batch_averages_t)

# 4. Reshape for Analysis by Sensor Type (5 sensor types, 6 readings each)
# To get sensor types as columns, we need shape (6, 5) where each column is a sensor type.
# The original reshape gave us this directly if we interpret rows as batches.
# If we needed to reshape differently to get sensor types as columns from the 1D data:
sensor_types_2d_t = sensor_data_1d_t.reshape(6, 5) # Same reshape works for this interpretation
print("\nReshaped for Sensor Type Analysis (6x5):\n", sensor_types_2d_t)
print("Shape:", tuple(sensor_types_2d_t.shape))


# 5. Calculate Sensor Type Averages (mean of each column)
sensor_type_averages_t = torch.mean(sensor_types_2d_t, dim=0) # dim=0 for mean across rows (each column)
print("\nSensor Type Averages:", sensor_type_averages_t)


--- Scenario 3: Data Analysis (PyTorch) ---
Original 1D Sensor Data: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28.,
        29., 30.])
Shape: (30,)

Reshaped into Batches (6x5):
 tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20.],
        [21., 22., 23., 24., 25.],
        [26., 27., 28., 29., 30.]])
Shape: (6, 5)

Batch Averages: tensor([ 3.,  8., 13., 18., 23., 28.])

Reshaped for Sensor Type Analysis (6x5):
 tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20.],
        [21., 22., 23., 24., 25.],
        [26., 27., 28., 29., 30.]])
Shape: (6, 5)

Sensor Type Averages: tensor([13.5000, 14.5000, 15.5000, 16.5000, 17.5000])


### **Scenario 1: Image Processing (TensorFlow)**

In [ ]:
# Scenario 1: Image Processing (TensorFlow Solution)
import tensorflow as tf
import numpy as np

print("--- Scenario 1: Image Processing (TensorFlow) ---")

# 1. Loading/Creating a Sample Image (5x5)
image_tf = tf.random.uniform(shape=(5, 5), minval=0, maxval=256, dtype=tf.float32)
print("Original Image Tensor:\n", image_tf.numpy())

# 2. Normalizing Pixel Values (0 to 1)
normalized_image_tf = image_tf / 255.0
print("\nNormalized Image Tensor:\n", normalized_image_tf.numpy())

# 3. Applying a Simple Filter (Element-wise multiplication of a 3x3 region)
kernel_tf = tf.constant([[1., 1., 1.],
                         [1., -8., 1.],
                         [1., 1., 1.]], dtype=tf.float32) # Example edge detection kernel

# Select a 3x3 region (e.g., top-left corner)
image_region_tf = normalized_image_tf[0:3, 0:3]
filtered_region_tf = image_region_tf * kernel_tf
print("\nSelected Image Region (3x3):\n", image_region_tf.numpy())
print("Kernel:\n", kernel_tf.numpy())
print("Filtered Region (Element-wise):\n", filtered_region_tf.numpy())

# 4. Calculating Average Brightness of the entire normalized image
average_brightness_tf = tf.reduce_mean(normalized_image_tf)
print("\nAverage Brightness of Normalized Image:", average_brightness_tf.numpy())

--- Scenario 1: Image Processing (TensorFlow) ---
Original Image Tensor:
 [[176.10016  124.02658  238.33456   64.559875 187.17542 ]
 [228.49747  242.36755  191.82953   89.40961  140.07874 ]
 [ 66.97061  178.51987   30.624207 136.91992  183.01358 ]
 [224.00455   86.95679   44.486725 113.114136 230.61148 ]
 [ 35.33789   31.278015 147.31497  241.07983  235.17657 ]]

Normalized Image Tensor:
 [[0.69058883 0.48637876 0.93464535 0.25317597 0.73402125]
 [0.8960685  0.950461   0.75227267 0.3506259  0.5493284 ]
 [0.26262984 0.7000779  0.12009493 0.5369409  0.7177003 ]
 [0.8784492  0.341007   0.17445774 0.44358486 0.90435874]
 [0.13857996 0.12265889 0.5777058  0.9454111  0.92226106]]

Selected Image Region (3x3):
 [[0.69058883 0.48637876 0.93464535]
 [0.8960685  0.950461   0.75227267]
 [0.26262984 0.7000779  0.12009493]]
Kernel:
 [[ 1.  1.  1.]
 [ 1. -8.  1.]
 [ 1.  1.  1.]]
Filtered Region (Element-wise):
 [[ 0.69058883  0.48637876  0.93464535]
 [ 0.8960685  -7.603688    0.75227267]
 [ 0.262629

### **Scenario 2: Data Analysis (TensorFlow)**

In [ ]:
# Scenario 2: Data Analysis (TensorFlow Solution)
import tensorflow as tf
import numpy as np

print("\n--- Scenario 3: Data Analysis (TensorFlow) ---")

# 1. Create Sensor Data (1D tensor, 30 elements)
sensor_data_1d_tf = tf.range(1, 31, dtype=tf.float32)
print("Original 1D Sensor Data:", sensor_data_1d_tf.numpy())
print("Shape:", sensor_data_1d_tf.shape)

# 2. Reshape into Batches (6 batches of 5 readings)
batches_2d_tf = tf.reshape(sensor_data_1d_tf, (6, 5))
print("\nReshaped into Batches (6x5):\n", batches_2d_tf.numpy())
print("Shape:", batches_2d_tf.shape)

# 3. Calculate Batch Averages (mean of each row)
batch_averages_tf = tf.reduce_mean(batches_2d_tf, axis=1) # axis=1 for mean across columns (each row)
print("\nBatch Averages:", batch_averages_tf.numpy())

# 4. Reshape for Analysis by Sensor Type (5 sensor types, 6 readings each)
# To get sensor types as columns, we need shape (6, 5) where each column is a sensor type.
# The original reshape gave us this directly if we interpret rows as batches.
# If we needed to reshape differently to get sensor types as columns from the 1D data:
sensor_types_2d_tf = tf.reshape(sensor_data_1d_tf, (6, 5)) # Same reshape works for this interpretation
print("\nReshaped for Sensor Type Analysis (6x5):\n", sensor_types_2d_tf.numpy())
print("Shape:", sensor_types_2d_tf.shape)

# 5. Calculate Sensor Type Averages (mean of each column)
sensor_type_averages_tf = tf.reduce_mean(sensor_types_2d_tf, axis=0) # axis=0 for mean across rows (each column)
print("\nSensor Type Averages:", sensor_type_averages_tf.numpy())


--- Scenario 3: Data Analysis (TensorFlow) ---
Original 1D Sensor Data: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]
Shape: (30,)

Reshaped into Batches (6x5):
 [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]
 [26. 27. 28. 29. 30.]]
Shape: (6, 5)

Batch Averages: [ 3.  8. 13. 18. 23. 28.]

Reshaped for Sensor Type Analysis (6x5):
 [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]
 [26. 27. 28. 29. 30.]]
Shape: (6, 5)

Sensor Type Averages: [13.5 14.5 15.5 16.5 17.5]


---
### Common Pitfalls
- Forgetting to enable GPU when you expect CUDA tensors (it’s optional for this lab).
- Using incompatible shapes for matrix multiplication (remember: `(m×n) @ (n×p) -> (m×p)`).
- Confusing reshape with transpose. Reshape only changes *view* of data size, not order.
- In PyTorch, missing `requires_grad=True` means gradients won’t be tracked.
